import { z } from "zod";

/**
 * Schema for anomaly alerts generated by Cloud Functions.
 */
export const alertSchema = z.object({
    id: z.string(),
    elderId: z.string(),
    guardianId: z.string(),
    type: z.enum(["fall_detected", "inactivity", "heart_rate_anomaly", "general"]),
    severity: z.enum(["low", "medium", "high", "critical"]),
    message: z.string(),
    anomalyScore: z.number().min(0).max(1),
    acknowledged: z.boolean().default(false),
    createdAt: z.number(),
});

export type Alert = z.infer<typeof alertSchema>;
